"""create initial tables

Revision ID: c167c8df701c
Revises: 
Create Date: 2025-06-01 15:50:31.797242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c167c8df701c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercializacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto', sa.String(length=40), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exportacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paises', sa.String(length=40), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paises', sa.String(length=40), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto', sa.String(length=40), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto', sa.String(length=40), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producao')
    op.drop_table('processamento')
    op.drop_table('importacao')
    op.drop_table('exportacao')
    op.drop_table('comercializacao')
    # ### end Alembic commands ###